In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [2]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

import time
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)

print("For loop: " + str(1000*(toc-tic)) + "ms")

249896.58677171788
Vectorized version: 1.1060237884521484ms
249896.58677173016
For loop: 192.30294227600098ms


In [19]:
a = np.matrix([[3],[1],[4]])
b = np.matrix([[4,2, 3], [2,5,4], [6,8,5]])
print(b)
print(a)
c = b.dot(a)
print("c: " + c.__str__())
 

[[4 2 3]
 [2 5 4]
 [6 8 5]]
[[3]
 [1]
 [4]]
c: [[26]
 [27]
 [46]]


In [27]:
import numpy as np

x = np.ones((3,3))
y = np.ones((1,3))

a = np.matrix([[1,2,3], [1,2,3], [1,2,3]])
a = np.array([[2,1], [1,3]])
b = np.matrix([[1],[2],[3],[4]])
print(x.shape())
print(a * a)
print(a ** 2 + a.T**2)

#print(np.dot(a,b))

[[4 1]
 [1 9]]
[[ 8  2]
 [ 2 18]]
